# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NRCS_MonthlySnow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Water_Year', models.PositiveSmallIntegerField()),
                ('Jan_collection_date', models.DateField(null=True)),
                ('Jan_snow_depth', models.PositiveSmallIntegerField(null=True)),
                ('Jan_snow_water_equivalent', models.PositiveSmallIntegerField(null=True)),
                ('Feb_collection_date', models.DateField(null=True)),
                ('Feb_snow_depth', models.PositiveSmallIntegerField(null=True)),
                ('Feb_snow_water_equivalent', models.PositiveSmallIntegerField(null=True)),
                ('Mar_collection_date', models.DateField(null=True)),
                ('Mar_snow_depth', models.PositiveSmallIntegerField(null=True)),
                ('Mar_snow_water_equivalent', models.PositiveSmallIntegerField(null=True)),
                ('Apr_collection_date', models.DateField(null=True)),
                ('Apr_snow_depth', models.PositiveSmallIntegerField(null=True)),
                ('Apr_snow_water_equivalent', models.PositiveSmallIntegerField(null=True)),
                ('May_collection_date', models.DateField(null=True)),
                ('May_snow_depth', models.PositiveSmallIntegerField(null=True)),
                ('May_snow_water_equivalent', models.PositiveSmallIntegerField(null=True)),
                ('Jun_collection_date', models.DateField(null=True)),
                ('Jun_snow_depth', models.PositiveSmallIntegerField(null=True)),
                ('Jun_snow_water_equivalent', models.PositiveSmallIntegerField(null=True)),
                ('Jul_collection_date', models.DateField(null=True)),
                ('Jul_snow_depth', models.PositiveSmallIntegerField(null=True)),
                ('Jul_snow_water_equivalent', models.PositiveSmallIntegerField(null=True)),
                ('Aug_collection_date', models.DateField(null=True)),
                ('Aug_snow_depth', models.PositiveSmallIntegerField(null=True)),
                ('Aug_snow_water_equivalent', models.PositiveSmallIntegerField(null=True)),
                ('Sep_collection_date', models.DateField(null=True)),
                ('Sep_snow_depth', models.PositiveSmallIntegerField(null=True)),
                ('Sep_snow_water_equivalent', models.PositiveSmallIntegerField(null=True)),
                ('Oct_collection_date', models.DateField(null=True)),
                ('Oct_snow_depth', models.PositiveSmallIntegerField(null=True)),
                ('Oct_snow_water_equivalent', models.PositiveSmallIntegerField(null=True)),
                ('Nov_collection_date', models.DateField(null=True)),
                ('Nov_snow_depth', models.PositiveSmallIntegerField(null=True)),
                ('Nov_snow_water_equivalent', models.PositiveSmallIntegerField(null=True)),
                ('Dec_collection_date', models.DateField(null=True)),
                ('Dec_snow_depth', models.PositiveSmallIntegerField(null=True)),
                ('Dec_snow_water_equivalent', models.PositiveSmallIntegerField(null=True)),
                ('Station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.NRCS_Locations')),
            ],
        ),
    ]
