# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 21:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_nrcs_monthlysnow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nrcs_monthlysnow',
            old_name='Station',
            new_name='location',
        ),
    ]
